package/strace: bump to version 5.18
update version to fix the compiler issue like below for the kernel 6.1:

xlat/fcntlcmds.h:53:7: error: ‘F_GETLK64’ undeclared here (not in a function); did you mean ‘F_GETLK’?
   53 |  XLAT(F_GETLK64),
      |       ^~~~~~~~~
xlat.h:64:54: note: in definition of macro ‘XLAT’
   64 | # define XLAT(val)                      { (unsigned)(val), #val }
      |                                                      ^~~

Signed-off-by: Andy Hu <andy.hu@starfivetech.com>